### ISSUE TITLE
Not working correctly in Apple M1 MacBook Pro 2020

### ISSUE THREAD

**Issue by kouml** [andresavic/AmongKey#12]
In my current M1 env, It's not working well because of the wrong position pressing.
I think it's good if you have a config about mouse pressing positions.

**Comment by andresavic** [comment]
Sorry for the late answer. AmongKey should automatically scale all position to the screen resolution. Do you have set the game controls to "Joystick" and changed the size of the Joystick to the smallest possible setting?
