### ISSUE TITLE
New Update(Starship) does not work on Macs with Touchbar

### ISSUE THREAD

**Issue by atw1020** [andresavic/AmongKey#13]
the Airship update causes the mouse to move to the top left corner of the screen instead of the bottom left corner of the screen.

**Comment by andresavic** [comment]
I already tested the AirShip update with the current version and didn't notice this happening. Can you please a screenrecoding?

**Comment by atw1020** [comment]
Here is a screen recording for you, I noticed that the update caused some other issues that I talk about in the video (be sure to have audio on)

<figure class="video_container">
  <iframe src="https://drive.google.com/file/d/1o9Hxz-0SbuMBwheKrJnzB4h-ylfVSdXG/view?usp=sharing" frameborder="0" allowfullscreen="true"> </iframe>
</figure>

**Comment by andresavic** [comment]
Awesome! I will take a closer look tomorrow. Just on question that would help, are you using Among Us on a secondary screen?

**Comment by atw1020** [comment]
I have a secondary screen on my setup but I was running among us and among key on my main screen

**Comment by andresavic** [comment]
I was able to reproduce this error and this only happens on macs with touchbar. Bug fix work in progress.

**Comment by andresavic** [comment]
Fix with #14
