### ISSUE TITLE
A and D keys not moving correctly

### ISSUE THREAD

**Issue by Canadianspruce** [andresavic/AmongKey#15]
Pressing A or D seems to move you up or down more than sideways.

**Comment by andresavic** [comment]
Do you mean when running sideways that the char is drifting?

**Comment by Canadianspruce** [comment]
Yes that’s correct. It’s happening on my Mac mini if that makes a difference. Instead of moving east or west. It’s more like south east and north west when moving.

**Comment by andresavic** [comment]
Can you please share a full screen screenshot or screen recording? That would be very helpful.

**Comment by Canadianspruce** [comment]
Hi Andre, I'm just an idiot and forget to reset the joystick to the minimum size after the last update. It's working great now.

Thanks!
