### ISSUE TITLE
Cursor keys not responding as they should on M1 MacBook Pro

### ISSUE THREAD

**Issue by miguelmanalo** [andresavic/AmongKey#4]
Hello! Just got a new MacBook Pro with M1. I've got the latest version of Among Key as of this writing but the cursor behavior doesn't seem to be working for me. Here's a YouTube video of what I'm seeing: https://www.youtube.com/watch?v=P7Mut8YlB5I&feature=youtu.be

In the video I am only controlling the character with the WASD keys.

Thanks for making this! It's rad.

**Comment by andresavic** [comment]
Fixed with #7
