### ISSUE TITLE
AmongKey is not working when Among us runs in fullscreen mode (macOS 11.1)

### ISSUE THREAD

**Issue by GiulianoCTRL** [andresavic/AmongKey#5]
How to recreate the issue:

1. Update to **macOS 11.1**.
2. Start Among Us and AmongKey.
3. Change to **fullscreen mode** (_feature in macOS 11.1_)
4. AmongKey does not seem to work (While **still running, nothing happens when pressing keys**)

Switching back to windowed gets AmongKey to work again.

Please let me know if you need further information.

**Comment by andresavic** [comment]
Fullscreen support comes with upcoming release.
